vaadin/magi-cli

bin/magi-release-notes
Instead of showing the blank page, let's show the API documentation :)
Before: https://cdn.vaadin.com/vaadin-progress-bar/1.0.0-alpha1/
After: https://cdn.vaadin.com/vaadin-progress-bar/1.0.0-alpha1/#/elements/vaadin-progress-bar
=> Improve the 'API documentation' link

bin/magi-p3-convert
This ugly workaround is needed to prevent us pushing the `resolutions` stuff to `p3-preview` branches and to use latest modulizer branch [vaadin-components-next](https://github.com/web-padawan/polymer-modulizer/commits/vaadin-components-next).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/10)
=> Pin polymer to modulizer compatible commit on master

dependency-map.json
This version no longer attempts to import `@polymer/polymer/lib/utils/import-href.js` which has been removed from Polymer in 3.0.1 patch release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/12)
=> Update dependency map for dev mode detector

bin/magi-p3-convert, package-lock.json, package.json
This is a quick fix for adjusting imports in generated P3 .js files.
There should be a solution in modulizer via a manifest.json but does not work yet. 
Connects to https://github.com/vaadin/components-team-tasks/issues/369
=> Use json file for magi-post actions

bin/magi-release
Current behavior: 
Expected: it should not fail and create release notes from the beginning
=> Do not fail if there are no releases before

bin/magi-release
Release name could be anything, and for `magi release-notes` the tag should be provided.
=> Use tag name instead of release name for magi release-notes

bin/magi-release
The same as https://github.com/vaadin/vaadin-element-skeleton/blob/master/.travis.yml#L56
`polymer-modulizer` produces random errors with `node_modules` folder presented:
=> Remove node_modules before p3-convert

lib/github-api.js
Connected to https://github.com/vaadin/vaadin-demo-helpers/pull/50 (the very first implementation of `semantic-release` + `magi`)
According to GitHub API docs http://github-tools.github.io/github/examples/authorization username isn't needed when authorizing with token.
Also, in order to work in TravisCI, `magi` should be able to use the `GH_TOKEN` environment variable.
=> GitHub API: support env.GH_TOKEN, remove excessive username

bin/magi-release
Fixes #68 
As per [docs](https://docs.npmjs.com/cli/publish#description):
> [--tag <tag>] Registers the published package with the given tag, such that npm install <name>@<tag> will install this version. By default, npm publish updates and npm install installs the latest tag. See npm-dist-tag for details about tags.
Previously we were not specifying `--tag` for `npm publish` which means we were always updating `latest`.
By adding `--tag` to `npm publish` we will ensure that only needed tag is updated: either `latest` or `next`, depending on the version number.
=> fix(release): add --tag to npm publish command, remove npm dist-tag

bin/magi-p3-convert, lib/p3-post.js
As a developer, I want to use the tagged template literals (instead of usual template literals) when converting to Polymer 3, in order to get the proper support for modern tools and plugins.
Requested in Polymer/polymer-modulizer#449 but I was unable to quickly implement it there.
```js
const $_documentContainer = document.createElement('template');
$_documentContainer.innerHTML = `<custom-style>
<style>
html {
--lumo-size-xs: 1.625rem;
--lumo-size-s: 1.875rem;
--lumo-size-m: 2.25rem;
--lumo-size-l: 2.75rem;
--lumo-size-xl: 3.5rem;
/* Icons */
--lumo-icon-size-s: 1.25em;
--lumo-icon-size-m: 1.5em;
--lumo-icon-size-l: 2.25em;
/* For backwards compatibility */
--lumo-icon-size: var(--lumo-icon-size-m);
}
</style>
</custom-style>`;
document.head.appendChild($_documentContainer.content);
``` …
=> Add default P3 post-process config to use html-tag

bin/magi-p3-convert
Fixed #72 
This will prevent npm publishing if something went wrong during `pe-convert`.
=> Add p3-convert verification

bin/magi-release
=> fix: do not warn about webjar when --skip-webjar

dependency-map.json
Connected to vaadin/vaadin-pdf-viewer#19
I was able to make Polymer 3 tests pass locally with that version, so let's include it here.
=> feat: use bundled-es-modules version of pdfjs-dist

bin/magi, bin/magi-check-bower, bin/magi-release, package-lock.json, package.json
Connected to vaadin/vaadin-element-skeleton#199
Can be tested by adding the following dependency:
```
"vaadin-select": "vaadin/vaadin-select#^2.1.0",
```
Output
```
$ magi check-bower
range /Users/sergey/vaadin/vaadin-element-skeleton/bower.json.dependencies.vaadin-select: '^2.1.0'
incorrectly resolved to: '2.1.0-alpha1'
possible correct range: '^2.1.0-alpha1'
Error: Bower has dependencies resolutions that violate semver and don't allow webjars.org deployment.
```
See vaadin/vaadin-element-skeleton#162 and vaadin/vaadin-element-skeleton#181
=> feat: add check-bower command to check version ranges

bin/magi-p3-convert
The following error starter do appear when running `magi p3-convert` locally:
```sh
husky > pre-commit (node v10.14.0)
npm ERR! missing script: lint
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sergey/.npm/_logs/2019-03-22T07_13_55_819Z-debug.log
husky > pre-commit hook failed (add --no-verify to bypass)
Git repo is dirty. Check all changes in to source control and then try again.
```
Note: in Travis it does not fail, as `husky` is properly detecting that `npm install` is running in CI environment, and skips setting up git hooks in that case. So this is only for local converting.
=> fix(p3-convert): delete husky git hooks config in package.json

bin/magi-release, bin/magi-update-version
I have just realised that in some cases we don't need to check version getters, especially for releasing mixins (e.g. `vaadin-list-mixin`), demo helpers etc. So updating script to move this part from `release` to `update-version` which should be only listed in package.json when needed.
=> fix: run check-version in update-version

package-lock.json, package.json
Recently there has been a number of security alerts from GitHub. 
This PR fixes these by temporarily dropping `semantic-release`.
Let's revert that once the linked issue is fixed.
<details>
<summary>Full report from running <code>npm audit</code> on master</summary>
<pre>
<code>
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘ …
=> chore(package): use npm-force-resolutions to fix audit warnings

bin/magi-p3-convert
This change is needed to make sure `yarn install --flat` works in Travis and make builds green.
=> fix: cleanup after generating TS defs

bin/magi-update-version
Some components, like vaadin-charts, mention the component version in multiple locations. 
Without this change only the first occurrence is updated.
Fixes #96
=> fix: replace all occurrences of version

bin/magi-p3-convert
Fixes #115 
If `@types/interfaces.d.ts` is found, add export line to the `d.ts` file corresponding to the main entrypoint specified as `"main"` field in `package.json`.
At this point we are sure that the entrypoint exists because we check for its presence:
https://github.com/vaadin/magi-cli/blob/89cf7757a1955b985eba19b5ceef3f0c262c35fb/bin/magi-p3-convert#L128-L129
=> fix(p3-convert): add export for TS interfaces

bin/magi-p3-convert, lib/p3-post.js
Include fix for `@attribute` JSDoc tags for properties needed by `web-component-analyzer`, see https://github.com/Polymer/tools/pull/3508
This is needed to fix https://github.com/vaadin/vaadin-grid/issues/1774 and https://github.com/vaadin/vaadin-combo-box/issues/896
=> fix: use custom gen-typescript-declarations

bin/magi-p3-convert
This is a finding from working on https://github.com/vaadin/vaadin-lumo-styles/pull/94
=> fix: handle markers inside theme mixins folders

bin/magi-p3-convert
This workaround is no longer needed as now we get Polymer 2.8.0 when running `bower install`.
=> feat: do not pin Polymer in p3-convert

bin/magi-deploy, bin/magi-release
1. Updated `deploy` script to take `--next` flag which will run the corresponding [build](https://bender.vaadin.com/viewType.html?buildTypeId=CoreElements_DeployTest_MdeployNext),
2. Updated `release` script to skip P3 conversion and webjar when publishing P3 components.
=> feat: release and deploy P3 components

bin/magi-update-version
Fixes #131
There was a problem in the regex, which was looking like this:  /2.0.0/g
It contains some unescaped `.` characters which results in the following replacements:
https://github.com/vaadin/vaadin-avatar/commit/dea89381995e5bfc918d86463fa9366e3b3cbc0e#diff-2021ab67f0e3ad122faeffcf7d2b1aaa676745cb545c089d534efd492735f40dL80-L81
Also, the single quotes around version are lacking which might also affect some files.
=> fix: use strict regex for version update

bin/magi-check-releases
Currently the check-releases command looks for commits that do not include `chore|docs|test|build|ci`. That means it will also report false positives, if an older commit did not use conventional commit messages.
This change reverses the filter to look explicitely for commits that should be released, which means they use conventional commit messages, and match `/^(fix|feat|refactor|docs):/`.
Testing this it:
- correctly ignores false positives, for example in:
- `vaadin-accordion` https://github.com/vaadin/vaadin-accordion/commits/master
- `vaadin-button` https://github.com/vaadin/vaadin-button/commits/master
- `vaadin-details` https://github.com/vaadin/vaadin-details/commits/master
- correctly reports unreleased changes, for example in:
- `vaadin-combobox` …
=> fix: make check-releases filter for commits that should be included

bin/magi-release
Adds a `--skip-npm-tag` option that prevents NPM from tagging the release as either `latest` or `next`. Note that npm publish does not actually allow disabling the tagging, so instead a catch-all dummy tag (`ignore`) is used for the release. Also when publishing from a branch that is not master, the dummy tag is used automatically. After publishing the package, the dummy tag is removed again.
If we go ahead with this, I'm going to update the release instructions for legacy components to add the flag for the release command.
Fixes: https://github.com/vaadin/magi-cli/issues/61
=> feat: allow skipping NPM tagging

CHANGELOG.md, bin/magi-p3-convert, lib/p3-post.js, package-lock.json, package.json
Connected to https://github.com/vaadin/components-team-tasks/issues/602
1. From now on, we assume that individual repositories keep `package-lock.json` in version control
2. Added logic to handle `package-lock-p3.json` renaming (the file needs to be created manually)
To use this feature, the following changes are needed:
1. Use this branch: https://github.com/vaadin/vaadin-component-dev-dependencies/tree/feat/lockfile
2. Remove `yarn install --flat` from the GitHub Actions P3 workflows due to [launchpad issue](https://github.com/vaadin/components-team-tasks/issues/602#issuecomment-1009736545).
- Feature
=> feat: enforce using lockfile in p3-convert

bin/magi-p3-convert, lib/p3-post.js
Updated to not override `"scripts"` section provided by custom `magi-p3-post.json` like in usage statistics.
Related to https://github.com/vaadin/vaadin-usage-statistics/issues/52
- Bugfix
=> fix: do not override custom p3-post scripts
