- dependency-map.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/platosha/magi-cli/2)
> Add the mapping for mock-http-request

- dependency-map.json
Needed for vaadin-date-picker P3 conversion
> Add dependency mapping for sugar.js

- bin/magi
- bin/magi-directory
This script needs to be run after a new version is tagged.
> Adding script for updating vaadin directory.

- dependency-map.json
Now using `1.0.0-pre.1`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/5)
> Update dependency map for ordered-layout

- dependency-map.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/6)
> Update dependency map for vaadin-text-field

- dependency-map.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/7)
> Update dependency map for vaadin-overlay

- dependency-map.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/8)
> Update dependency map for vaadin-list-box

- dependency-map.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/11)
> Update dependency map to latest P3 components

- bin/magi-p3-convert
- package-lock.json
- package.json
Fixes #13 
Examples:
```
<link rel="import" href="../../foo/foo.html">
/* MAGI ADD START
console.log("polymer 3");
MAGI ADD END */
/* MAGI REMOVE START */
console.log("polymer 2");
/* MAGI REMOVE END */
```
> Adding support for MAGI markers

- dependency-map.json
Connects to https://github.com/vaadin/vaadin-material-styles/issues/68
> Add material-styles version mapping

- bin/magi-p3-convert
Connected to https://github.com/vaadin/vaadin-development-mode-detector/issues/17
> remove magi-p3-post.json after run

- bin/magi-p3-convert
Fixes https://github.com/vaadin/vaadin-usage-statistics/issues/22
> do not add a dependency to Polymer if the package did not have one

- bin/magi-release
- lib/tools.js
- package-lock.json
- package.json
This PR adds the cross-platform support for `magi`.
Used this SO answer to copy-paste: https://stackoverflow.com/a/35561971/1331425
Credits to https://github.com/moxystudio/node-cross-spawn
> Use cross-spawn for cross platform compatibility

- bin/magi-p3-convert
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/41)
> Keep existing bower resolutions for P3 conversion

- bin/magi-release
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/46)
> Add an option to skip CDN deployment for internal dependencies

- bin/magi-release
When we dont have any index.html means that we dont have any api or anything to show to the user
> Skip cdn if there is no index.html

- .travis.yml
- README.md
- package-lock.json
- package.json
- release.config.js
Used plugins:
- https://github.com/semantic-release/changelog
- https://github.com/semantic-release/git
- https://github.com/semantic-release/npm
> Initialize semantic-release

- .travis.yml
> chore(ci): run Travis build on master only

- bin/magi-release
Fixes #57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/59)
> Tag npm version as next in case it is not stable

- bin/magi
- lib/tools.js
- package-lock.json
- package.json
> Add update-notifier, remind about new magi releases

- dependency-map.json
Related to vaadin/vaadin-pdf-viewer#19
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/magi-cli/78)
> feat(p3): add pdfjs-dist to modulizer dependency map

- .vscode/launch.json
Since the majority of us using VS Code, it makes sense to share the debug config.
For now, this contains only the configuration for `magi-p3-convert`. Later, I'll add other configurations, but I'd like to get your early feedback guys.
> Add VS Code debug configuration (launch.json)

- bin/magi-release
Fixes https://github.com/vaadin/magi-cli/issues/81
> Only tag releases from master

- bin/magi
- bin/magi-check-version
- bin/magi-release
- package-lock.json
- package.json
Connected to vaadin/vaadin-element-skeleton#199
> feat: add check-version command for components getters

- bin/magi
- bin/magi-update-version
Connected to vaadin/vaadin-element-skeleton#199
> feat: add update-version command for npm preversion

- bin/magi-p3-convert
Fixes https://github.com/vaadin/vaadin-text-field/issues/396
Fixes https://github.com/vaadin/base-starter-angular/issues/25
> Remove extends annotations after modularization

- bin/magi
- bin/magi-check-events-docs
Connected to https://github.com/vaadin/components-team-tasks/issues/476
> Annotation for *-changed events

- bin/magi-update-version
> feat: support updating version in .ts files

- bin/magi-p3-convert
- lib/p3-post.js
Fixes #105 
This PR is as draft. Will test how it works for mixins locally, and then mark as ready for review.
> feat: generate TypeScript definitions

- bin/magi-p3-convert
> fix: filter files in p3-post for duplicates

- lib/p3-post.js
See https://github.com/Polymer/tools/issues/3536
> fix: update resolutions for yarn flat

- bin/magi-update-version
This is needed for P3 conversion setup.
> feat: allow to update version in .js files

- lib/bender-api.js
Fixes #129
Replaces usage of username/password with a token. 
This is the preferred approach according to TeamCity documentation.
See https://www.jetbrains.com/help/teamcity/rest/teamcity-rest-api-documentation.html#General+Usage+Principles
> Use token for authentication in bender

- bin/magi
- bin/magi-check-releases
Fixes https://github.com/vaadin/components-team-tasks/issues/599
> Consider conventional commits names and platform branch/version

- bin/magi-p3-convert
Pre-requisite for https://github.com/vaadin/vaadin-charts/pull/617
- Fix
> fix: update DOMPurify dependency mapping for P3
